bluetusk/config/routes.rb
Bluetusk::Application.routes.draw do
  resources :devices

  root :to => 'scan#index', :as => 'scan'

end

bluetusk/app/models/device.rb
class Device < ActiveRecord::Base
end

bluetusk/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

bluetusk/app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  # GET /devices
  # GET /devices.xml
  def index
    @devices = Device.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @devices }
    end
  end

  # GET /devices/1
  # GET /devices/1.xml
  def show
    @device = Device.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @device }
    end
  end

  # GET /devices/new
  # GET /devices/new.xml
  def new
    @device = Device.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @device }
    end
  end

  # GET /devices/1/edit
  def edit
    @device = Device.find(params[:id])
  end

  # POST /devices
  # POST /devices.xml
  def create
    @device = Device.new(params[:device])

    respond_to do |format|
      if @device.save
        format.html { redirect_to(@device, :notice => 'Device was successfully created.') }
        format.xml  { render :xml => @device, :status => :created, :location => @device }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @device.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /devices/1
  # PUT /devices/1.xml
  def update
    @device = Device.find(params[:id])

    respond_to do |format|
      if @device.update_attributes(params[:device])
        format.html { redirect_to(@device, :notice => 'Device was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @device.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.xml
  def destroy
    @device = Device.find(params[:id])
    @device.destroy

    respond_to do |format|
      format.html { redirect_to(devices_url) }
      format.xml  { head :ok }
    end
  end
end

bluetusk/app/controllers/scan_controller.rb
class ScanController < ApplicationController
  def index
    @feliz = "Muerete"
    @scanned = `hcitool scan`
  end
end

bluetusk/app/helpers/application_helper.rb
module ApplicationHelper
end

bluetusk/app/helpers/devices_helper.rb
module DevicesHelper
end

bluetusk/app/helpers/scan_helper.rb
module ScanHelper
end

bluetusk/app/views/devices/_form.html.erb
<%= form_for(@device) do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :mac %><br />
    <%= f.text_field :mac %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :last_seen %><br />
    <%= f.datetime_select :last_seen %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

bluetusk/app/views/devices/edit.html.erb
<h1>Editing device</h1>

<%= render 'form' %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

bluetusk/app/views/devices/index.html.erb
<h1>Listing devices</h1>

<table>
  <tr>
    <th>Mac</th>
    <th>Name</th>
    <th>Last seen</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @devices.each do |device| %>
  <tr>
    <td><%= device.mac %></td>
    <td><%= device.name %></td>
    <td><%= device.last_seen %></td>
    <td><%= link_to 'Show', device %></td>
    <td><%= link_to 'Edit', edit_device_path(device) %></td>
    <td><%= link_to 'Destroy', device, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Device', new_device_path %>

bluetusk/app/views/devices/new.html.erb
<h1>New device</h1>

<%= render 'form' %>

<%= link_to 'Back', devices_path %>

bluetusk/app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Mac:</b>
  <%= @device.mac %>
</p>

<p>
  <b>Name:</b>
  <%= @device.name %>
</p>

<p>
  <b>Last seen:</b>
  <%= @device.last_seen %>
</p>


<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>

bluetusk/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bluetusk</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

bluetusk/app/views/scan/index.html.erb
<p>
Hola mundo
</p>
<p>
<%=@feliz %>
<pre>
<%=@scanned %>
</pre>
</p>